/* eslint-disable */
/* global WebImporter */
/**
 * Parser for cards-steps. Base: cards.
 * Source: https://agibank.com.br/conta-corrente
 *   main > section[class="flex flex-col items-center bg-[var(--slice-bg-color)] py-[42px]"]
 * Structure (blocks/cards-steps): 1 column, one row per step -> [instruction text].
 *   The step number is generated by the block, so the source number badge is dropped.
 * Selectors verified in migration-work/block-context/cards-steps/source.html:
 *   div (leaf, text "1" / "2" / "3")  -> number badge; its parent div is the step card
 *   step card > div > p              -> instruction (inline links kept)
 * Content outside the steps (section h2 "Abra sua conta em minutos", trailing "Pronto! ..." p)
 * is kept as default content: placed before the block when it precedes the steps, after otherwise.
 */
const NUMBER_RE = /^\s*\d{1,2}\s*[.)]?\s*$/;

function cleanText(node) {
  return node.textContent.replace(/\s+/g, ' ').trim();
}

function collectDefaultContent(element, steps, document) {
  const before = [];
  const after = [];
  const nodes = [...element.querySelectorAll('h1, h2, h3, h4, h5, h6, p, a[href]')]
    .filter((n) => !steps.some((s) => s.contains(n)));
  nodes.forEach((n) => {
    // eslint-disable-next-line no-bitwise
    const bucket = (n.compareDocumentPosition(steps[0]) & 4) ? before : after;
    const tag = n.tagName.toLowerCase();
    if (tag === 'a') {
      if (n.closest('p, h1, h2, h3, h4, h5, h6')) return;
      const text = cleanText(n);
      if (!text) return;
      const link = document.createElement('a');
      link.href = n.getAttribute('href');
      link.textContent = text;
      const p = document.createElement('p');
      p.append(link);
      bucket.push(p);
      return;
    }
    if (n.closest('a') || !cleanText(n)) return;
    if (/^h[1-6]$/.test(tag)) {
      n.querySelectorAll('br').forEach((br) => br.replaceWith(' '));
      const h = document.createElement(tag);
      h.textContent = cleanText(n);
      bucket.push(h);
    } else {
      bucket.push(n);
    }
  });
  return { before, after };
}

export default function parse(element, { document }) {
  // Number badges: leaf elements whose whole text is a step number
  const badges = [...element.querySelectorAll('div, span')]
    .filter((el) => !el.children.length && NUMBER_RE.test(el.textContent));
  let steps = badges.map((b) => b.parentElement).filter((s, i, arr) => s && arr.indexOf(s) === i);
  if (!steps.length) {
    // Fallback: an ordered list
    steps = [...element.querySelectorAll('ol > li')];
  }

  const cells = [];
  steps.forEach((step) => {
    const content = [];
    const paras = [...step.querySelectorAll('p')].filter((p) => cleanText(p));
    if (paras.length) {
      content.push(...paras);
    } else {
      const text = [...step.childNodes]
        .filter((n) => !badges.includes(n))
        .map((n) => n.textContent).join(' ').replace(/\s+/g, ' ').trim();
      if (text) {
        const p = document.createElement('p');
        p.textContent = text;
        content.push(p);
      }
    }
    if (content.length) cells.push([content]);
  });

  if (!cells.length) {
    element.replaceWith(...element.childNodes);
    return;
  }

  const { before, after } = collectDefaultContent(element, steps, document);
  if (before.length) element.before(...before);
  if (after.length) element.after(...after);

  const block = WebImporter.Blocks.createBlock(document, { name: 'cards-steps', cells });
  element.replaceWith(block);
}
